### PR TITLE
Fixes #26 [ Killing ptop properly while exiting ]

### LINKED ISSUE #26: Kill ptop properly
In case any exception occurs, exception should be logged properly and ptop should be killed properly will all of the threads ( gui and sensor threads ) killed properly.

### PR DESCRIPTION
**Pull request by vinusankars**
Kill ptop properly.

### CODE REVIEW

**Comment by darxtrix** [comment]
> Proposed solution is to kill ptop while by using psutil during a quit action.

**Comment by darxtrix** [comment]
This is not required as ptop is already quitting gracefully, a global ` global_stop_event = threading.Event()` is being passed to all the sensors which is getting used for making ptop exit gracefully. Line 41, main.py Let me know if you have any further queries otherwise we can close it.

**Comment by vinusankars** [comment]
I guess this is required. As ptop was being killed on my PC, it returned to the terminal. But again on calling ptop on the same terminal, 2 ptop processes are visible in the processes. I think this is because the previous ptop was not killed.

**Comment by vinusankars** [comment]
Yes, you are right. It works fine, exits fine. Now we can close the issue.

**Pull request closed without merging**
