### PR TITLE
Fixes #34 [ Python3 compatibility issue ]

### LINKED ISSUE #34: Python 3 compatability issue
Ptop does not work with python 3

### PR DESCRIPTION
**Pull request by vinusankars**
Python 3 compatibility issue

### CODE REVIEW

**Comment by deeps-nars** [comment]
@darxtrix, could you please look through these pull requests? I chose to add it individually because it would be better for you to look into the issues.

**Comment by darxtrix** [comment]
Yes, I have a plan to add all of these changes tomorrow. Sadly, my laptop broke down and couldn't take a look over them earlier.

**Comment by darxtrix** [comment]
Hi @vinusankars @deeps-nars I am using manjaro linux distro and having problems with the display of Braille unicode characters that is used to render the charts. Interestingly all other unicode set is working fine except the Braille character. Hence, I am blocked on the issues. I have posted on the manjaro forums and is waiting for any workarounds. Attaching a screenshot:
ptop-braille-issue

Meanwhile thinking to spin up an ubuntu VM or a chrome extension terminal where braille is rendering properly. Sorry for the delay and thanks for the patience.

**Comment by darxtrix** [comment]
Hi @vinusankars @deeps-nars can you guys tell what fonts (system fonts) you guys are using ?

**Comment by darxtrix** [comment]
@vinusankars looks great, just want to factor out the time conversion function before merging.

**Comment by vinusankars** [comment]
@darxtrix thabk you! My pleasure.

**Comment by vinusankars** [comment]
Cool, great!

**Pull request merged**
