### PR TITLE
Fixes #18 [ Added network bandwidth monitoring ]

### LINKED ISSUE #18: Add network stats
Add incoming and outgoing bandwidth to ptop

### PR DESCRIPTION
**Pull request by smeet20**
Add Network Stats

### CODE REVIEW

**Comment by smeet20** [comment]
@darxtrix Can you look into this updated code showing the Network Usage plot too? The plot has been made using the npyscreen as lehar was not working correctly because of its resizing issue

**Comment by darxtrix** [comment]
Sure @smeet20. I have added a comment to post a photo of the UI so that I can have a look over the visuals once. It would be great if that can be done.

**Comment by darxtrix** [comment]
@smeet20 , please add a few screenshots of the network graph.

**Comment by smeet20** [comment]
The screenshot showing the Network Usag Plot has been added in the file. You can probably have a look at it.



[NetworkPlot.docx](https://github.com/darxtrix/ptop/files/2576427/NetworkPlot.docx)

**Comment by darxtrix** [comment]
Thanks for uploading the sceenshot. The original problem still persists. There is no any upper bound to a network sensor when compared to a cpu or memory sensor which is capped to 100%. So, we have to do relative ordering of data here. You can read more about it here: https://hackernoon.com/visualizing-data-in-terminal-using-lehar-7cfded09c1ad 

Anyways, you have do the overhead work of packet counting. Let me add a widget below the Overview widget for displaying the network information. I will add a few commits to this PR and will merge over it. Thanks !

**Comment by darxtrix** [comment]
Thanks @smeet20 for the contribution, for the moment i am adding the network speed to the overview widget only. I merged your commits using https://github.com/darxtrix/ptop/pull/50

**Pull request closed without merging**
